/**
 * ppm_pgm_io.c —— Netpbm PPM(P3/P6)/PGM(P2/P5) 读写
 *
 * P6/P5 = 二进制；P3/P2 = ASCII文本；maxval默认255。
 * 头部格式：魔数 + 注释行(可选，#开头) + width + height + maxval
 */
#include "imageproc.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* 跳过空白和#注释，读下一个整数 */
static int read_int(FILE *fp) {
    int ch, v = 0, started = 0;
    while ((ch = fgetc(fp)) != EOF) {
        if (ch == '#') { while ((ch = fgetc(fp)) != EOF && ch != '\n'); continue; }
        if (isspace(ch)) { if (started) break; continue; }
        if (isdigit(ch)) { v = v*10 + (ch-'0'); started = 1; }
        else break;
    }
    return v;
}
static int read_magic(FILE *fp) {
    int c1 = fgetc(fp), c2 = fgetc(fp);
    if (c1 != 'P') return 0;
    return (c1<<8) | c2;
}

IpStatus ip_ppm_load(const char *path, Image **out) {
    if (!path || !out) return IP_ERR_NULL_PTR;
    FILE *fp = fopen(path, "rb");
    if (!fp) return IP_ERR_FILE_OPEN;
    int magic = read_magic(fp);
    if (magic != ('P'<<8|'6') && magic != ('P'<<8|'3')) { fclose(fp); return IP_ERR_INVALID_FMT; }
    int w = read_int(fp), h = read_int(fp), maxv = read_int(fp);
    if (w<=0 || h<=0 || maxv!=255) { fclose(fp); return IP_ERR_CORRUPTED; }
    /* read_int 在读完数字后已消费了分隔空白符，流指针恰好指向下一个token/数据。
     * 但 maxv 之后可能紧接 '#' 注释行（P6规范允许），先跳过。 */
    int ch;
    while ((ch = fgetc(fp)) != EOF) {
        if (ch == '#') { while ((ch=fgetc(fp))!=EOF && ch!='\n'); continue; }
        if (isspace(ch)) continue;
        ungetc(ch, fp); break;
    }

    Image *img = NULL;
    IpStatus s = ip_image_create(w, h, IP_FMT_RGB24, &img);
    if (s != IP_OK) { fclose(fp); return s; }

    size_t total = (size_t)w*h*3;
    if (magic == ('P'<<8|'6')) {
        /* P6二进制，RGB顺序，我们内部也是RGB，直接读 */
        if (fread(img->data, 1, total, fp) != total) {
            ip_image_release(&img); fclose(fp); return IP_ERR_CORRUPTED;
        }
    } else { /* P3 文本，也是RGB顺序 */
        for (size_t i = 0; i < total; i++) {
            int v; if (fscanf(fp, "%d", &v) != 1) {
                ip_image_release(&img); fclose(fp); return IP_ERR_CORRUPTED;
            }
            img->data[i] = (uint8_t)v;
        }
    }
    fclose(fp);
    *out = img;
    return IP_OK;
}

IpStatus ip_ppm_save(const char *path, const Image *img, int binary) {
    if (!path || !img) return IP_ERR_NULL_PTR;
    if (img->fmt != IP_FMT_RGB24) return IP_ERR_INVALID_FMT;
    FILE *fp = fopen(path, "wb");
    if (!fp) return IP_ERR_FILE_OPEN;
    int w = img->width, h = img->height;
    if (binary) {
        fprintf(fp, "P6\n# Generated by imageproc\n%d %d\n255\n", w, h);
        fwrite(img->data, 1, (size_t)w*h*3, fp);
    } else {
        fprintf(fp, "P3\n# Generated by imageproc\n%d %d\n255\n", w, h);
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                fprintf(fp, "%d %d %d ", IP_R(img,x,y), IP_G(img,x,y), IP_B(img,x,y));
            }
            fprintf(fp, "\n");
        }
    }
    fclose(fp);
    return IP_OK;
}

IpStatus ip_pgm_load(const char *path, Image **out) {
    if (!path || !out) return IP_ERR_NULL_PTR;
    FILE *fp = fopen(path, "rb");
    if (!fp) return IP_ERR_FILE_OPEN;
    int magic = read_magic(fp);
    if (magic != ('P'<<8|'5') && magic != ('P'<<8|'2')) { fclose(fp); return IP_ERR_INVALID_FMT; }
    int w = read_int(fp), h = read_int(fp), maxv = read_int(fp);
    if (w<=0 || h<=0 || maxv!=255) { fclose(fp); return IP_ERR_CORRUPTED; }
    int ch;
    while ((ch = fgetc(fp)) != EOF) {
        if (ch == '#') { while ((ch=fgetc(fp))!=EOF && ch!='\n'); continue; }
        if (isspace(ch)) continue;
        ungetc(ch, fp); break;
    }
    Image *img = NULL;
    IpStatus s = ip_image_create(w, h, IP_FMT_GRAY8, &img);
    if (s != IP_OK) { fclose(fp); return s; }
    if (magic == ('P'<<8|'5')) {
        if (fread(img->data, 1, (size_t)w*h, fp) != (size_t)w*h) {
            ip_image_release(&img); fclose(fp); return IP_ERR_CORRUPTED;
        }
    } else {
        for (int i = 0; i < w*h; i++) {
            int v; if (fscanf(fp, "%d", &v)!=1) {
                ip_image_release(&img); fclose(fp); return IP_ERR_CORRUPTED;
            }
            img->data[i] = (uint8_t)v;
        }
    }
    fclose(fp);
    *out = img;
    return IP_OK;
}

IpStatus ip_pgm_save(const char *path, const Image *img, int binary) {
    if (!path || !img) return IP_ERR_NULL_PTR;
    if (img->fmt != IP_FMT_GRAY8) return IP_ERR_INVALID_FMT;
    FILE *fp = fopen(path, "wb");
    if (!fp) return IP_ERR_FILE_OPEN;
    int w = img->width, h = img->height;
    if (binary) {
        fprintf(fp, "P5\n# Generated by imageproc\n%d %d\n255\n", w, h);
        fwrite(img->data, 1, (size_t)w*h, fp);
    } else {
        fprintf(fp, "P2\n# Generated by imageproc\n%d %d\n255\n", w, h);
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                fprintf(fp, "%d ", IP_GRAY(img,x,y));
            }
            fprintf(fp, "\n");
        }
    }
    fclose(fp);
    return IP_OK;
}
